coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 2%
    patch:
      default:
        target: 60%

comment:
  layout: "reach, diff, flags, files"
  behavior: default

ignore:
  - "**/*_test.rs"
  - "**/tests/**"
  - "crates/server/src/interpreter.rs"
  # These files are basically giant TODO lists
  - "crates/server/src/workspace.rs"
  - "crates/server/src/features/code_actions.rs"
